# Generated by Django 3.0 on 2022-06-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='msg',
            new_name='message',
        ),
    ]
