# Generated by Django 3.0 on 2022-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20220630_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drname', models.CharField(max_length=50)),
                ('drpost', models.CharField(max_length=50)),
                ('drabout', models.TextField()),
                ('drimage', models.ImageField(upload_to='drimage')),
            ],
        ),
    ]
