# Generated by Django 3.0 on 2022-07-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('upost', models.CharField(max_length=50)),
                ('ufeedback', models.TextField()),
                ('uimage', models.ImageField(upload_to='userimage')),
            ],
        ),
    ]
